name: ethereum

profile: ethereum

seed-paths: ['seeds']
model-paths: ['models']
macro-paths: ['macros']

clean-targets:
  - 'target'
  - 'dbt_packages'

flags:
  fail_fast: true

seeds:
  ethereum:
    +schema: raw

models:
  ethereum:
    +static_analysis: strict
    +materialized: table
    +tags: ['eth', 'crypto']
    marts:
      +tags:
        - powerbi
        - report

vars:
  token_name_var: 'link'
  token_address_var: '0x514910771af9ca656af840dff83e8264ecf986ca'
  token_decimals_var: '18'

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['ethereum', 'dbt_utils']
